formatter: "markdown table" # this is required

version: ""

header-from: main.tf

recursive:
  enabled: false
  path: modules

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    <img src="https://raw.githubusercontent.com/Lupus-Metallum/brand/master/images/logo.jpg" width="400"/>

    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: "outputs.tf"

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true